name: Update Zen

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main

      - run: ./update.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update packages"
          push_options: '--force'